# Generated by Django 2.1.2 on 2018-10-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one_code', models.TextField(blank=True, null=True, verbose_name='Player one code')),
                ('player_two_code', models.TextField(blank=True, null=True, verbose_name='Player two code')),
                ('last_connected', models.IntegerField(default=1, verbose_name='Last player connected')),
            ],
        ),
    ]
