# Generated by Django 2.1.2 on 2018-10-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='round_number',
            field=models.IntegerField(default=1, verbose_name='Round number'),
        ),
    ]
