# Generated by Django 2.1.2 on 2018-10-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laby', '0002_games_round_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1, verbose_name='Round number')),
                ('player_one_code', models.TextField(blank=True, null=True, verbose_name='Player one code')),
                ('player_two_code', models.TextField(blank=True, null=True, verbose_name='Player two code')),
                ('last_active', models.IntegerField(default=1, verbose_name='Last player')),
            ],
        ),
        migrations.DeleteModel(
            name='Games',
        ),
    ]
