# Generated by Django 2.1.2 on 2018-10-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laby', '0003_auto_20181011_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='player_one_code',
            field=models.TextField(blank=True, default='', verbose_name='Player one code'),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='player_two_code',
            field=models.TextField(blank=True, default='', verbose_name='Player two code'),
        ),
    ]
