# Generated by Django 2.1.2 on 2018-10-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laby', '0004_auto_20181011_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='over',
            field=models.BooleanField(default=False, verbose_name='Round over'),
        ),
    ]
