# Generated by Django 2.1.2 on 2018-10-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laby', '0005_rounds_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='round_number',
            field=models.IntegerField(default=0, verbose_name='Round number'),
        ),
    ]
