# Generated by Django 2.1.2 on 2018-10-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laby', '0006_auto_20181011_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='p_one_submitted',
            field=models.BooleanField(default=False, verbose_name='Player one submitted code'),
        ),
        migrations.AddField(
            model_name='rounds',
            name='p_two_submitted',
            field=models.BooleanField(default=False, verbose_name='Player two submitted code'),
        ),
    ]
