# Generated by Django 2.1.2 on 2018-10-11 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laby', '0008_auto_20181011_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom de la partie')),
                ('over', models.BooleanField(default=False, verbose_name='Game over')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='Pseudo')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_one', to='laby.Player', verbose_name='Joueur un'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_two', to='laby.Player', verbose_name='Joueur deux'),
        ),
        migrations.AddField(
            model_name='rounds',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='laby.Game'),
            preserve_default=False,
        ),
    ]
