# Generated by Django 2.1.2 on 2018-10-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laby', '0009_auto_20181011_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nom de la partie'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=50, unique=True, verbose_name='Pseudo'),
        ),
    ]
