# Generated by Django 2.1.2 on 2018-10-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laby', '0010_auto_20181011_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='p_one_ran',
            field=models.BooleanField(default=False, verbose_name='Player one ran code'),
        ),
        migrations.AddField(
            model_name='rounds',
            name='p_two_ran',
            field=models.BooleanField(default=False, verbose_name='Player two ran code'),
        ),
    ]
